# configs/dongjak.yaml

# path
root_dir: ./data/dongjak
train:
  src_dir: ./data/dongjak/train
  tgt_dir: ./data/dongjak/test/test18
eval:
  src_dir: ./data/dongjak/eval/eval01
  tgt_dir: ./data/dongjak/test/test18
test:
  src_dir: ./data/dongjak/eval/eval03
  tgt_dir: ./data/dongjak/test/test18

# overide default.yaml
ae:
  svdd_lambda: 1.0

# original path
orig_dir:
  src_dir: ./data/dongjak(original)_girder/normal
  tgt_dir: ./data/dongjak(original)_girder/test
  s1_dir: ./data/dongjak(original)_girder/s1
  s2_dir: ./data/dongjak(original)_girder/s2

noise:
  save_dir: ./data/dongjak(original)_girder
  src_scale: 1.5
  tgt_scale: 0.5
  random_seed: 42
  src_iter: 1
  tgt_iter: 5

# preprocess parameters
preprocess:
  sr: 100
  nsample: 1024
  n_fft: 256
  hop_length: 6
  window: hann
  nsplit: 1722  # normal to train, eval split ratio(float) or number(int)