# configs/dongjak.yaml

# path
root_dir: ./data/dongjak
train:
  src_dir: ./data/dongjak/train
  tgt_dir: ./data/dongjak/test/test18
eval:
  src_dir: ./data/dongjak/eval/eval01
  tgt_dir: ./data/dongjak/test/test18
test:
  src_dir: ./data/dongjak/eval/eval03
  tgt_dir: ./data/dongjak/test/test18

# overide default.yaml
ae:
  recon_type: mse