# configs/esc50.yaml

# path
root_dir: ./data/ESC50
train:
  src_dir: ./data/ESC50/train
  tgt_dir: ./data/ESC50/test/test40
eval:
  src_dir: ./data/ESC50/eval/eval01
  tgt_dir: ./data/ESC50/test/test40
test:
  src_dir: ./data/ESC50/eval/eval02
  tgt_dir: ./data/ESC50/test/test40

# overide default.yaml
ae:
  svdd_lambda: 1.0